name: Gradle Release

on:
  release:
    types: [ created ]

jobs:
  release:
    name: "Release"
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
      checks: write
      # only needed unless run with comment_mode: off
      pull-requests: write

    if: success()

    steps:
      - uses: ./.github/workflows/gradle-build.yml